project_name: blockspeed

release:
  prerelease: auto

builds:
  - 
    main: .
    id: bs6
    binary: bs6
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

nfpms:
  -
    vendor: Distributed Works
    homepage: https://distrib.works
    maintainer: Victor Castell <victor@distrib.works>
    description: Blockchain performance testing platform based on k6
    license: AGPL-3.0

    formats:
      - deb
      - rpm

    overrides:
      rpm:
        replacements:
          amd64: x86_64

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - image_templates:
      - ghcr.io/distribworks/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: amd64
    ids: &docker-ids
      - bs6
    build_flag_templates:
      - --platform=linux/amd64

  - image_templates:
      - ghcr.io/distribworks/{{ .ProjectName }}:{{ .Version }}-arm64
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: arm64
    ids: *docker-ids
    build_flag_templates:
      - --platform=linux/arm64/v8

docker_manifests:
  - name_template: ghcr.io/distribworks/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/distribworks/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/distribworks/{{ .ProjectName }}:{{ .Version }}-arm64v8

  - name_template: gcr.io/distribworks/{{ .ProjectName }}:latest
    image_templates:
    - ghcr.io/distribworks/{{ .ProjectName }}:{{ .Version }}-amd64
    - ghcr.io/distribworks/{{ .ProjectName }}:{{ .Version }}-arm64

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^Merge pull request'
