
version: '3.4'

networks:
  blockspeed:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - blockspeed
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=blockspeed

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    image: gcr.io/distribworks/blockspeed:latest
    networks:
      - blockspeed
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/blockspeed
    volumes:
      - ./examples:/scripts
